name: Production CI/CD Pipeline

on:
  push:
    branches: [ main, feature/* ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Validate
        run: |
          cd terraform/vpc && terraform init -backend=false && terraform validate
          cd ../iam && terraform init -backend=false && terraform validate
          cd ../eks && terraform init -backend=false && terraform validate

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@d527181cbe16c31f82f2560e4fbc11bcff5779c1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Validate Kubernetes Manifests
        run: |
          kubectl apply --dry-run=client -f k8s-manifests/deployment/deployment.yaml
          kubectl apply --dry-run=client -f k8s-manifests/service/Service.yaml

      - name: Build Docker Artifact
        run: |
          docker build -t production-app:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: BUILD AND PUSH Docker image
        uses: docker/build-push-action@ca5286e6c4779e930113008609b5331451e04dbd
        with:
          context: .
          push: true
          tags: |
            rajagopaldevops/production-app:${{ github.sha }}
            rajagopaldevops/production-app:latest